### PR TITLE
Proposal #33, #28

### PR DESCRIPTION
**Pull request by hlide**
The `MOV` instruction is implemented as `ADDUI Rd, Rs, 0` or `ORI Rd, Rs, 0` by MIPS and offered through pseudo `MOVE`.

It is a shade that we can not use the remaining bit fields for something useful. Here we implement it as an useful addition in the form following: `D <- S + sext8(V)` which means you can add a register value with a signed immediate value and store the result in another register in one instruction. It happens we can also get cheap MOV, INC and DEC as pseudos with that form. Name for the replacing instruction is MVR (MoVe Register).

### CODE REVIEW

**Comment by hlide** [comment]
I'm a little confused with Pull request. I wanted to make two pull requests - one per proposal but I failed to do so.

**Comment by francisrstokes** [comment]
The normal approach is to create multiple branches from master. For example:

- `feature/proposal-33`
- `feature/proposal-28`

That ensures the changes are made in isolation. For now it's most likely fine but for next time. I will review the code this morning

**Review by francisrstokes — CHANGES_REQUESTED** [review]
This is great, really awesome work. If you can update the readme to reflect the new instruction set I'll merge it immediately.

**Comment by hlide** [comment]
README.md updated with instruction set changes.

**Pull request merged**
